/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;


import Controller.BANHANGDAO;
import Model.HoaDon;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author minhd
 */
public class DOANHTHUPanel extends javax.swing.JPanel {
    DefaultTableModel tableModel;
    BANHANGDAO orderinfo;

    public DOANHTHUPanel() {
        initComponents();
        orderinfo = new BANHANGDAO();

        String[] cols = new String[]{
            "ID Hóa Đơn", "Thời Gian", "ID Khách Hàng", "ID Người Dùng",
            "Tổng tiền gốc", "Mức giảm giá", "Tổng tiền"
        };
        tableModel = new DefaultTableModel(cols, 0);
        jTable1.setModel(tableModel);

        FIlter.addActionListener(this::filterActionPerformed);

        loadAllHoaDon();
    }

    private void loadAllHoaDon() {
        try {
            jLabel1.setText(String.valueOf(orderinfo.getcountHoaDon()));
            jLabel2.setText(formatCurrency(orderinfo.gettotalHoaDon()));
            List<HoaDon> listHD = orderinfo.getAllHoaDon();
            updateTableData(listHD);
        } catch (Exception e) {
            showThongBaoLoi("Lỗi khi tải toàn bộ hóa đơn!", e);
        }
    }

    private void loadHoaDonTheoNgay(String day1, String month1, String year1, String day2, String month2, String year2) {
        try {
            jLabel1.setText(String.valueOf(orderinfo.getcountHoaDondate(day1, month1, year1, day2, month2, year2)));
            jLabel2.setText(formatCurrency(orderinfo.gettotalHoaDondate(day1, month1, year1, day2, month2, year2)));
            List<HoaDon> listHD = orderinfo.getAllHoaDondate(day1, month1, year1, day2, month2, year2);
            updateTableData(listHD);
        } catch (Exception e) {
            showThongBaoLoi("Lỗi khi lọc hóa đơn theo ngày!", e);
        }
    }

    private void updateTableData(List<HoaDon> listHD) {
        tableModel.setRowCount(0);
        for (HoaDon hd : listHD) {
            Object[] row = new Object[]{
                hd.getId(),
                hd.getThoiGian(),
                hd.getIdKhachHang(),
                hd.getIdNguoiDung(),
                hd.getTongTienGoc(),
                hd.getMucGiamGia(),
                hd.getTongTienSauGiamGia()
            };
            tableModel.addRow(row);
        }
    }

    private void showThongBaoLoi(String message, Exception e) {
        Logger.getLogger(DOANHTHUPanel.class.getName()).log(Level.SEVERE, message, e);
        JOptionPane.showMessageDialog(this, message + "\nChi tiết: " + e.getMessage(),
                "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    private void filterActionPerformed(ActionEvent evt) {
        String year1 = jcbNamBatDau.getText().trim();
        String year2 = jcbNamKetThuc.getText().trim();

        if (year1.isEmpty() || year2.isEmpty()) {
            loadAllHoaDon();
            return;
        }

        try {
            Integer.valueOf(year1);
            Integer.valueOf(year2);
        } catch (NumberFormatException ex) {
            showThongBaoLoi("Vui lòng nhập đúng định dạng năm (số)", ex);
            return;
        }

        String day1 = jcbNgayBatDau.getSelectedItem().toString();
        String month1 = jcbThangBatDau.getSelectedItem().toString();

        String day2 = jcbNgayKetThuc.getSelectedItem().toString();
        String month2 = jcbThangKetThuc.getSelectedItem().toString();

        loadHoaDonTheoNgay(day1, month1, year1, day2, month2, year2);
    }

    private String formatCurrency(Object value) {
        try {
            return String.format("%,d VNĐ", ((Number) value).longValue());
        } catch (Exception e) {
            return value.toString();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jcbNgayBatDau = new javax.swing.JComboBox<>();
        jcbThangBatDau = new javax.swing.JComboBox<>();
        jcbNamBatDau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbNgayKetThuc = new javax.swing.JComboBox<>();
        jcbThangKetThuc = new javax.swing.JComboBox<>();
        jcbNamKetThuc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FIlter = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        setInheritsPopupMenu(true);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Hóa Đơn", "Thời gian", "ID Khách Hàng", "ID Người Dùng", "Tổng tiền gốc", "Mức giảm giá", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 73, 609, 275));

        jLabel6.setText("Từ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 41, -1, -1));

        jcbNgayBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(jcbNgayBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 38, 48, -1));

        jcbThangBatDau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jcbThangBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbThangBatDauActionPerformed(evt);
            }
        });
        add(jcbThangBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 38, 48, -1));

        jcbNamBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNamBatDauActionPerformed(evt);
            }
        });
        add(jcbNamBatDau, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 38, 91, -1));

        jLabel7.setText("Đến:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 41, -1, -1));

        jcbNgayKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(jcbNgayKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 38, 48, -1));

        jcbThangKetThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jcbThangKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbThangKetThucActionPerformed(evt);
            }
        });
        add(jcbThangKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 38, 48, -1));

        jcbNamKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNamKetThucActionPerformed(evt);
            }
        });
        add(jcbNamKetThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 38, 100, -1));

        jLabel8.setText("Số đơn:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 360, -1, -1));

        jLabel9.setText("Tổng tiền:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 387, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 387, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 360, -1, -1));

        FIlter.setBackground(new java.awt.Color(41, 62, 80));
        FIlter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FIlter.setForeground(new java.awt.Color(255, 255, 255));
        FIlter.setText("Tìm kiếm");
        add(FIlter, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 38, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bmonthActionPerformed

    private void byearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_byearActionPerformed

    private void EmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmonthActionPerformed

    private void EyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EyearActionPerformed

    private void jcbThangBatDauActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:        
    }

    private void jcbNamBatDauActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:        
    }

    private void jcbThangKetThucActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:        
    }

    private void jcbNamKetThucActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:        
    }

    private void FIlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIlterActionPerformed

    }//GEN-LAST:event_FIlterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FIlter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jcbNamBatDau;
    private javax.swing.JTextField jcbNamKetThuc;
    private javax.swing.JComboBox<String> jcbNgayBatDau;
    private javax.swing.JComboBox<String> jcbNgayKetThuc;
    private javax.swing.JComboBox<String> jcbThangBatDau;
    private javax.swing.JComboBox<String> jcbThangKetThuc;
    // End of variables declaration//GEN-END:variables
}
