/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.QLNVDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.NhanVien;

public class Login extends javax.swing.JFrame {



    /**
     * Creates new form Login
     */
    QLNVDAO qlnv = new QLNVDAO();
    private final char defaultEchoChar;

    public Login() {
        initComponents();
        defaultEchoChar = txtMatKhau.getEchoChar();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private final KiemTraThongTin ktttInstance = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jbtDangNhap = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();
        jCheckBox = new javax.swing.JCheckBox();
        jbtQuenMatKhau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(41, 120, 185));
        jLabel2.setText("Đăng Nhập");

        jLabel3.setText("Email:");

        jLabel4.setText("Mật khẩu:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jbtDangNhap.setBackground(new java.awt.Color(41, 120, 185));
        jbtDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        jbtDangNhap.setText("Đăng nhập");
        jbtDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangNhapActionPerformed(evt);
            }
        });

        jCheckBox.setText("Hiện mật khẩu");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });

        jbtQuenMatKhau.setForeground(new java.awt.Color(41, 120, 185));
        jbtQuenMatKhau.setText("--- Quên mật khẩu? ---");
        jbtQuenMatKhau.setBorder(null);
        jbtQuenMatKhau.setBorderPainted(false);
        jbtQuenMatKhau.setFocusPainted(false);
        jbtQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQuenMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMatKhau)
                                    .addComponent(jCheckBox)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtDangNhap)
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtQuenMatKhau)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtDangNhap)
                .addGap(12, 12, 12)
                .addComponent(jbtQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void jbtDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangNhapActionPerformed
        String email = txtEmail.getText().trim();
        String matKhau = new String(txtMatKhau.getPassword()).trim();

        if (email.isEmpty()) {
            showErrorMessage("Vui lòng nhập ID!");
            txtEmail.requestFocus();
            return;
        }
        
        if (matKhau.isEmpty()) {
            showErrorMessage("Vui lòng nhập mật khẩu!");
            txtMatKhau.requestFocus();
            return;
        }

        try {
            NhanVien authenticatedUser = authenticateUser(email, matKhau);
            
            if (authenticatedUser != null) {
                // Kiểm tra vai trò của người dùng và mở trang tương ứng
                if (isManager(authenticatedUser)) {
                    // Nếu là quản lý, mở TrangChu
                    new TrangChu(authenticatedUser).setVisible(true);
                } else {
                    // Nếu là nhân viên, mở TrangChu1
                    new TrangChu1(authenticatedUser).setVisible(true);
                }
                this.dispose();
            } else {
                showErrorMessage("Sai ID hoặc mật khẩu!");
                clearFields();
            }
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            showErrorMessage("Lỗi hệ thống khi đăng nhập!");
        }
    }//GEN-LAST:event_jbtDangNhapActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        txtMatKhau.setEchoChar(jCheckBox.isSelected() ? (char) 0 : '*');
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void jbtQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQuenMatKhauActionPerformed
        new KiemTraThongTin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtQuenMatKhauActionPerformed

    
    private NhanVien authenticateUser(String email, String matKhau) throws SQLException, ClassNotFoundException {
        for (NhanVien n : qlnv.getAll()) {
            if (matKhau.equals(n.getMatKhau()) && email.equals(n.getEmail())) {
                return n;
            } else {
            }
        }
        return null;
    }
    
    /**
     * Kiểm tra xem người dùng có phải là quản lý hay không
     * @param nhanVien đối tượng nhân viên cần kiểm tra
     * @return true nếu là quản lý, false nếu là nhân viên
     */
    private boolean isManager(NhanVien nhanVien) {
        try {
            String chucVu = nhanVien.getChucVu();
            return "Quản lý".equalsIgnoreCase(chucVu) || 
                   "Manager".equalsIgnoreCase(chucVu) || 
                   "Admin".equalsIgnoreCase(chucVu);
        } catch (Exception e) {
            String email = nhanVien.getEmail();
            return email.contains("manager") || 
                   email.contains("admin") || 
                   email.contains("ql");
        }
    }
    
    private void showErrorMessage(String message) {
        javax.swing.JOptionPane.showMessageDialog(this,
                message,
                "Thông báo",
                javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    private void clearFields() {
        txtMatKhau.setText("");
        txtEmail.requestFocus();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtDangNhap;
    private javax.swing.JButton jbtQuenMatKhau;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
