/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import model.NhanVien;

public class TrangChu extends javax.swing.JFrame {

    public TrangChu(NhanVien nv) {
        initComponents();
        setupFullscreen();
    }

    private TrangChu() {
        initComponents();
        setupFullscreen();
    }

    private void setupFullscreen() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtQLNV = new javax.swing.JButton();
        jbtQLSP = new javax.swing.JButton();
        jbtQLHD = new javax.swing.JButton();
        jbtQLNL = new javax.swing.JButton();
        jbtQLKH = new javax.swing.JButton();
        jbtQLKM = new javax.swing.JButton();
        jbtDangXuat = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtQLNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLNV.setText("Nhân Viên");
        jbtQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLNVActionPerformed(evt);
            }
        });

        jbtQLSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLSP.setText("Sản Phẩm");
        jbtQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLSPActionPerformed(evt);
            }
        });

        jbtQLHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLHD.setText("Hóa Đơn");
        jbtQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLHDActionPerformed(evt);
            }
        });

        jbtQLNL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLNL.setText("Nguyên Liệu");
        jbtQLNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLNLActionPerformed(evt);
            }
        });

        jbtQLKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLKH.setText("Khách Hàng");
        jbtQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLKHActionPerformed(evt);
            }
        });

        jbtQLKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLKM.setText("Khuyến Mại");
        jbtQLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLKMActionPerformed(evt);
            }
        });

        jbtDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtDangXuat.setText("Đăng Xuất");
        jbtDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangXuatActionPerformed(evt);
            }
        });

        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtQLHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtQLNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLNL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtDangXuat)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLSPActionPerformed
        QLSPPanel p2 = new QLSPPanel();
        p2.setSize(820, 474);
        p2.setLocation(0, 0);

        jPanel.removeAll();
        jPanel.add(p2, BorderLayout.CENTER);
        jPanel.repaint();
        jPanel.revalidate();
    }//GEN-LAST:event_jbtQLSPActionPerformed

    private void jbtQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLNVActionPerformed
        QLNVPanel p1 = new QLNVPanel();
        p1.setSize(820, 474);
        p1.setLocation(0, 0);

        jPanel.removeAll();
        jPanel.add(p1, BorderLayout.CENTER);
        jPanel.repaint();
        jPanel.revalidate();
    }//GEN-LAST:event_jbtQLNVActionPerformed

    private void jbtQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLHDActionPerformed

    }//GEN-LAST:event_jbtQLHDActionPerformed

    private void jbtQLNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLNLActionPerformed
        QLNLPanel p4 = new QLNLPanel();
        p4.setSize(908, 333);
        p4.setLocation(0, 0);

        jPanel.removeAll();
        jPanel.add(p4, BorderLayout.CENTER);
        jPanel.repaint();
        jPanel.revalidate();
    }//GEN-LAST:event_jbtQLNLActionPerformed

    private void jbtQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLKHActionPerformed
        QLKHPanel p5 = new QLKHPanel();
        p5.setSize(908, 333);
        p5.setLocation(0, 0);

        jPanel.removeAll();
        jPanel.add(p5, BorderLayout.CENTER);
        jPanel.repaint();
        jPanel.revalidate();
    }//GEN-LAST:event_jbtQLKHActionPerformed

    private void jbtQLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLKMActionPerformed
        QLKMPanel p6 = new QLKMPanel();
        p6.setSize(1001, 682);
        p6.setLocation(0, 0);

        jPanel.removeAll();
        jPanel.add(p6, BorderLayout.CENTER);
        jPanel.repaint();
        jPanel.revalidate();        // TODO add your handling code here:
    }//GEN-LAST:event_jbtQLKMActionPerformed

    private void jbtDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangXuatActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất không ?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            this.dispose();

            SwingUtilities.invokeLater(() -> {
                new Login().setVisible(true);
            });
        }
    }//GEN-LAST:event_jbtDangXuatActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TrangChu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel;
    private javax.swing.JButton jbtDangXuat;
    private javax.swing.JButton jbtQLHD;
    private javax.swing.JButton jbtQLKH;
    private javax.swing.JButton jbtQLKM;
    private javax.swing.JButton jbtQLNL;
    private javax.swing.JButton jbtQLNV;
    private javax.swing.JButton jbtQLSP;
    // End of variables declaration//GEN-END:variables
}
