/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.NhanVien;

public class TrangChu extends javax.swing.JFrame {

    private NhanVien loggedInUser;

    public TrangChu(NhanVien n) {
        this.loggedInUser = n;
        initComponents();
        setFullScreen();
        displayUserInfo();
    }

    private TrangChu() {
        initComponents();
        setFullScreen();
    }

    private void setFullScreen() {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    // Method to display logged-in user information
    private void displayUserInfo() {
        if (loggedInUser != null) {
            jLabel1.setText("Xin chào: " + loggedInUser.getTenDayDu());
        } else {
            jLabel1.setText("Chưa đăng nhập");
        }
    }

    // Getter method to access logged-in user from other panels
    public NhanVien getLoggedInUser() {
        return loggedInUser;
    }

    private void showPanel(JPanel panel) {
        displayPanel(panel);
    }

    private void displayPanel(JPanel panel) {
        jPanel.removeAll();
        jPanel.setLayout(new BorderLayout());
        jPanel.add(panel, BorderLayout.CENTER);
        jPanel.revalidate();
        jPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        jbtQLSP = new javax.swing.JButton();
        jbtQLNV = new javax.swing.JButton();
        jbtTRANGCHU = new javax.swing.JButton();
        jbtLOAISANPHAM = new javax.swing.JButton();
        jbtQLHD = new javax.swing.JButton();
        jbtQLKH = new javax.swing.JButton();
        jbtLOAIKHACHHANG = new javax.swing.JButton();
        jbtQLKM = new javax.swing.JButton();
        jbtDOANHTHU = new javax.swing.JButton();
        jbtDangXuat = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jbtBANHANG = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 62, 80));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        navigationPanel.setBackground(new java.awt.Color(41, 62, 80));
        navigationPanel.setForeground(new java.awt.Color(255, 255, 255));

        jbtQLSP.setBackground(new java.awt.Color(44, 62, 80));
        jbtQLSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLSP.setForeground(new java.awt.Color(255, 255, 255));
        jbtQLSP.setText("Sản Phẩm");
        jbtQLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLSPActionPerformed(evt);
            }
        });

        jbtQLNV.setBackground(new java.awt.Color(44, 62, 80));
        jbtQLNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLNV.setForeground(new java.awt.Color(255, 255, 255));
        jbtQLNV.setText("Nhân Viên");
        jbtQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLNVActionPerformed(evt);
            }
        });

        jbtTRANGCHU.setBackground(new java.awt.Color(44, 62, 80));
        jbtTRANGCHU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtTRANGCHU.setForeground(new java.awt.Color(255, 255, 255));
        jbtTRANGCHU.setText("Trang Chủ");
        jbtTRANGCHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTRANGCHUActionPerformed(evt);
            }
        });

        jbtLOAISANPHAM.setBackground(new java.awt.Color(44, 62, 80));
        jbtLOAISANPHAM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtLOAISANPHAM.setForeground(new java.awt.Color(255, 255, 255));
        jbtLOAISANPHAM.setText("Loại Sản Phẩm");
        jbtLOAISANPHAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLOAISANPHAMActionPerformed(evt);
            }
        });

        jbtQLHD.setBackground(new java.awt.Color(44, 62, 80));
        jbtQLHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLHD.setForeground(new java.awt.Color(255, 255, 255));
        jbtQLHD.setText("Hóa Đơn");
        jbtQLHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLHDActionPerformed(evt);
            }
        });

        jbtQLKH.setBackground(new java.awt.Color(44, 62, 80));
        jbtQLKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLKH.setForeground(new java.awt.Color(255, 255, 255));
        jbtQLKH.setText("Khách Hàng");
        jbtQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLKHActionPerformed(evt);
            }
        });

        jbtLOAIKHACHHANG.setBackground(new java.awt.Color(44, 62, 80));
        jbtLOAIKHACHHANG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtLOAIKHACHHANG.setForeground(new java.awt.Color(255, 255, 255));
        jbtLOAIKHACHHANG.setText("Loại Khách Hàng");
        jbtLOAIKHACHHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLOAIKHACHHANGActionPerformed(evt);
            }
        });

        jbtQLKM.setBackground(new java.awt.Color(44, 62, 80));
        jbtQLKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtQLKM.setForeground(new java.awt.Color(255, 255, 255));
        jbtQLKM.setText("Khuyến Mại");
        jbtQLKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtQLKMActionPerformed(evt);
            }
        });

        jbtDOANHTHU.setBackground(new java.awt.Color(44, 62, 80));
        jbtDOANHTHU.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtDOANHTHU.setForeground(new java.awt.Color(255, 255, 255));
        jbtDOANHTHU.setText("Doanh Thu");
        jbtDOANHTHU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDOANHTHUActionPerformed(evt);
            }
        });

        jbtDangXuat.setBackground(new java.awt.Color(255, 0, 0));
        jbtDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtDangXuat.setForeground(new java.awt.Color(255, 255, 255));
        jbtDangXuat.setText("Đăng Xuất");
        jbtDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDangXuatActionPerformed(evt);
            }
        });

        jPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 723, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        jbtBANHANG.setBackground(new java.awt.Color(44, 62, 80));
        jbtBANHANG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtBANHANG.setForeground(new java.awt.Color(255, 255, 255));
        jbtBANHANG.setText("Bán Hàng");
        jbtBANHANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBANHANGActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(41, 62, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtLOAIKHACHHANG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(jbtQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtLOAISANPHAM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtDOANHTHU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtBANHANG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtTRANGCHU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtTRANGCHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLSP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLOAISANPHAM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLOAIKHACHHANG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtQLKM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtDOANHTHU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBANHANG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtDangXuat))
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(navigationPanel, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtQLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLSPActionPerformed
        showPanel(new QLSPPanel());
    }//GEN-LAST:event_jbtQLSPActionPerformed

    private void jbtQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLNVActionPerformed
        showPanel(new QLNVPanel());
    }//GEN-LAST:event_jbtQLNVActionPerformed

    private void jbtQLHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLHDActionPerformed
        showPanel(new QLHDPanel());
    }//GEN-LAST:event_jbtQLHDActionPerformed

    private void jbtQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLKHActionPerformed
        showPanel(new QLKHPanel());
    }//GEN-LAST:event_jbtQLKHActionPerformed

    private void jbtQLKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtQLKMActionPerformed
        showPanel(new QLKMPanel());
    }//GEN-LAST:event_jbtQLKMActionPerformed

    private void jbtDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDangXuatActionPerformed
        int option = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất không ?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            this.dispose();

            SwingUtilities.invokeLater(() -> {
                new Login().setVisible(true);
            });
        }
    }//GEN-LAST:event_jbtDangXuatActionPerformed

    private void jbtDOANHTHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDOANHTHUActionPerformed
        showPanel(new DOANHTHUPanel());
    }//GEN-LAST:event_jbtDOANHTHUActionPerformed

    private void jbtLOAISANPHAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLOAISANPHAMActionPerformed
        showPanel(new QLLSPPanel());
    }//GEN-LAST:event_jbtLOAISANPHAMActionPerformed

    private void jbtLOAIKHACHHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLOAIKHACHHANGActionPerformed
        showPanel(new QLHKHPanel());
    }//GEN-LAST:event_jbtLOAIKHACHHANGActionPerformed

    private void jbtTRANGCHUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTRANGCHUActionPerformed

    }//GEN-LAST:event_jbtTRANGCHUActionPerformed

    private void jbtBANHANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBANHANGActionPerformed
        showPanel(new BHpanel(loggedInUser));
    }//GEN-LAST:event_jbtBANHANGActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> {
            new TrangChu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtBANHANG;
    private javax.swing.JButton jbtDOANHTHU;
    private javax.swing.JButton jbtDangXuat;
    private javax.swing.JButton jbtLOAIKHACHHANG;
    private javax.swing.JButton jbtLOAISANPHAM;
    private javax.swing.JButton jbtQLHD;
    private javax.swing.JButton jbtQLKH;
    private javax.swing.JButton jbtQLKM;
    private javax.swing.JButton jbtQLNV;
    private javax.swing.JButton jbtQLSP;
    private javax.swing.JButton jbtTRANGCHU;
    private javax.swing.JPanel navigationPanel;
    // End of variables declaration//GEN-END:variables
}
